name: Firebase CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - run: npm install -g yarn
      - name: yarn add, build and test
        run: yarn add
          yarn build
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
